apiVersion: v1
kind: Template
metadata:
  name: simpleflask-template
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    name: simpleflask
  spec:
    containers:
    - envFrom: 
        - configMapRef:
            generateName: ${CONFIG_MAP}-
      image: ${DOCKER_IMAGE}
      name: simpleflask
      ports:
      - containerPort: 8000
        protocol: TCP
parameters:
- description: configmap to use for environment variables
  name: CONFIG_MAP
- description: docker image to be used
  name: DOCKER_IMAGE