apiVersion: v1
kind: Template
metadata:
  name: simpleflask-template
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    name: ${POD_NAME}
  spec:
    containers:
    - envFrom: 
        - configMapRef:
            name: ${CONFIG_MAP}
      image: ${DOCKER_IMAGE}
      name: simpleflask
      ports:
      - containerPort: 8000
        protocol: TCP
parameters:
- description: configmap to use for environment variables
  name: CONFIG_MAP
- description: docker image to be used
  name: DOCKER_IMAGE
- description: name of pod to be deployed
  name: POD_NAME
  value: simpleflask